/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.guinumeroparole;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import static java.lang.String.valueOf;

/**
 *
 * @author feder
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        GridLayout layout = (GridLayout) jPanel1.getLayout();
    }
    String testo;

    //aggiungere il calcolo del tempo
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        labelCaratteri = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        labelSpazi = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        labelPunti = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        labelVirgole = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabelLettere = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        labelNumeri = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        labelAltriCaratteri = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        labelMSTotali = new javax.swing.JLabel();
        labelMSSpazi = new javax.swing.JLabel();
        labelMSPunti = new javax.swing.JLabel();
        labelMSVirgole = new javax.swing.JLabel();
        LABEL_LETTERE = new javax.swing.JLabel();
        labelMSNumeri = new javax.swing.JLabel();
        labelMSAltriCaratteri = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 170, 100));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new java.awt.GridLayout(10, 3));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("CARATTERI TOTALI:");
        jPanel1.add(jLabel5);

        labelCaratteri.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        labelCaratteri.setForeground(new java.awt.Color(255, 0, 51));
        labelCaratteri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelCaratteri);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 5));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner1.setMaximumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(jSpinner1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("SPAZI:");
        jPanel1.add(jLabel7);

        labelSpazi.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        labelSpazi.setForeground(new java.awt.Color(255, 0, 51));
        labelSpazi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelSpazi);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 5));
        jSpinner2.setMaximumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(jSpinner2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("PUNTI:");
        jPanel1.add(jLabel3);

        labelPunti.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        labelPunti.setForeground(new java.awt.Color(255, 0, 0));
        labelPunti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelPunti);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 5));
        jSpinner3.setMaximumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(jSpinner3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("VIRGOLE:");
        jPanel1.add(jLabel4);

        labelVirgole.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        labelVirgole.setForeground(new java.awt.Color(255, 0, 0));
        labelVirgole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelVirgole);

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 5));
        jSpinner4.setMaximumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(jSpinner4);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("LETTERE:");
        jPanel1.add(jLabel13);

        jLabelLettere.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabelLettere.setForeground(new java.awt.Color(255, 0, 0));
        jLabelLettere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelLettere);

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 5));
        jSpinner5.setMaximumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(jSpinner5);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("NUMERI:");
        jPanel1.add(jLabel10);

        labelNumeri.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        labelNumeri.setForeground(new java.awt.Color(255, 0, 51));
        labelNumeri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelNumeri);

        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 5));
        jSpinner6.setMaximumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(jSpinner6);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("ALTRI CARATTERI:");
        jPanel1.add(jLabel11);

        labelAltriCaratteri.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        labelAltriCaratteri.setForeground(new java.awt.Color(255, 0, 0));
        labelAltriCaratteri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelAltriCaratteri);

        jSpinner7.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 5));
        jSpinner7.setMaximumSize(new java.awt.Dimension(60, 60));
        jPanel1.add(jSpinner7);

        jPanel2.setBackground(new java.awt.Color(255, 170, 100));
        jPanel2.setLayout(new java.awt.GridLayout(10, 1));

        labelMSTotali.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMSTotali.setForeground(new java.awt.Color(255, 0, 0));
        labelMSTotali.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(labelMSTotali);

        labelMSSpazi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMSSpazi.setForeground(new java.awt.Color(255, 0, 0));
        labelMSSpazi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(labelMSSpazi);

        labelMSPunti.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMSPunti.setForeground(new java.awt.Color(255, 0, 0));
        labelMSPunti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(labelMSPunti);

        labelMSVirgole.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMSVirgole.setForeground(new java.awt.Color(255, 0, 0));
        labelMSVirgole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(labelMSVirgole);

        LABEL_LETTERE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LABEL_LETTERE.setForeground(new java.awt.Color(255, 0, 0));
        LABEL_LETTERE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(LABEL_LETTERE);

        labelMSNumeri.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMSNumeri.setForeground(new java.awt.Color(255, 0, 0));
        labelMSNumeri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(labelMSNumeri);

        labelMSAltriCaratteri.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelMSAltriCaratteri.setForeground(new java.awt.Color(255, 0, 0));
        labelMSAltriCaratteri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(labelMSAltriCaratteri);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("MILLISECONDI TOTALI:");

        labelTotal.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(255, 0, 51));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        testo = jTextArea1.getText();
        int lunghezza = 0, punti = 0, virgole = 0, caratteri = 0, spazi = 0, numeri = 0, altro = 0;
        jLabel3.setBackground(Color.red);
        lunghezza = testo.length();
        Character[] testoVet = new Character[lunghezza];
        for (int i = 0; i < lunghezza; i++) {
            testoVet[i] = testo.charAt(i);

        }

        for (Character c : testoVet) {
            if (c == ' ') {
                spazi++;
            }
            if (c.isAlphabetic(c)) {
                caratteri++;
            }
            if (c.isDigit(c)) {
                numeri++;
            }
            if (c == '.') {
                punti++;
            }
            if (c == ',') {
                virgole++;
            }
            if (c != '.' && c != ',' && !c.isDigit(c) && !c.isAlphabetic(c) && c != ' ') {
                altro++;
            }

        }
        labelCaratteri.setText(String.valueOf(lunghezza));
        labelPunti.setText(String.valueOf(punti));
        labelVirgole.setText(String.valueOf(virgole));
        labelNumeri.setText(String.valueOf(numeri));
        labelSpazi.setText(String.valueOf(spazi));
        labelAltriCaratteri.setText(String.valueOf(altro));
        jLabelLettere.setText(String.valueOf(caratteri));
        
        int temp = (Integer)this.jSpinner5.getValue() * caratteri;
        LABEL_LETTERE.setText(String.valueOf(temp)+" ms");
        
        labelMSNumeri.setText(String.valueOf((Integer)this.jSpinner6.getValue() * numeri)+" ms");
        labelMSAltriCaratteri.setText(String.valueOf((Integer)this.jSpinner7.getValue() * altro)+" ms");
        labelMSPunti.setText(String.valueOf((Integer)this.jSpinner3.getValue() * punti)+" ms");
        labelMSVirgole.setText(String.valueOf((Integer)this.jSpinner4.getValue() * virgole)+" ms");
        labelMSSpazi.setText(String.valueOf((Integer)this.jSpinner2.getValue() * spazi)+" ms");
        LABEL_LETTERE.setText(String.valueOf((Integer)this.jSpinner1.getValue() * lunghezza)+" ms");
        int totMillisec = (Integer)this.jSpinner5.getValue() * caratteri + (Integer)this.jSpinner6.getValue() * numeri + (Integer)this.jSpinner7.getValue() * altro + (Integer)this.jSpinner3.getValue() * punti + (Integer)this.jSpinner4.getValue() * virgole + (Integer)this.jSpinner2.getValue() * spazi + (Integer)this.jSpinner1.getValue() * lunghezza;
        labelTotal.setText(String.valueOf(totMillisec));
        
       
        

        


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABEL_LETTERE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLettere;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAltriCaratteri;
    private javax.swing.JLabel labelCaratteri;
    private javax.swing.JLabel labelMSAltriCaratteri;
    private javax.swing.JLabel labelMSNumeri;
    private javax.swing.JLabel labelMSPunti;
    private javax.swing.JLabel labelMSSpazi;
    private javax.swing.JLabel labelMSTotali;
    private javax.swing.JLabel labelMSVirgole;
    private javax.swing.JLabel labelNumeri;
    private javax.swing.JLabel labelPunti;
    private javax.swing.JLabel labelSpazi;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelVirgole;
    // End of variables declaration//GEN-END:variables
}
